from zojax.django.socialauthentication.settings import FACEBOOK_API_KEY,\
    ENABLE_OPENID_REGISTRATION, ENABLE_TWITTER_REGISTRATION,\
    ENABLE_FACEBOOK_REGISTRATION


def settings(request):
    data = {
        'ENABLE_OPENID_REGISTRATION': ENABLE_OPENID_REGISTRATION,
        'ENABLE_TWITTER_REGISTRATION': ENABLE_TWITTER_REGISTRATION,
        'ENABLE_FACEBOOK_REGISTRATION': ENABLE_FACEBOOK_REGISTRATION,
        'FACEBOOK_API_KEY': FACEBOOK_API_KEY,
    }
    return data