from django.conf import settings

ENABLE_OPENID_REGISTRATION = getattr(settings, 'ENABLE_TWITER_REGISTRATION', True)
ENABLE_TWITTER_REGISTRATION = getattr(settings, 'ENABLE_TWITER_REGISTRATION', True)
ENABLE_FACEBOOK_REGISTRATION = getattr(settings, 'ENABLE_FACEBOOK_REGISTRATION', True)

TWITTER_CONSUMER_KEY = getattr(settings, 'TWITTER_CONSUMER_KEY', "")
TWITTER_CONSUMER_SECRET = getattr(settings, 'TWITTER_CONSUMER_SECRET', "")

if not TWITTER_CONSUMER_KEY or not TWITTER_CONSUMER_SECRET:
    ENABLE_TWITTER_REGISTRATION = False

FACEBOOK_API_KEY = getattr(settings, 'FACEBOOK_API_KEY', "")
FACEBOOK_API_SECRET = getattr(settings, 'FACEBOOK_API_SECRET', "")

if not FACEBOOK_API_KEY or not FACEBOOK_API_SECRET:
    ENABLE_FACEBOOK_REGISTRATION = False
